org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.34
forge_version_range=[36.2.34,37)
loader_version_range=[36,)

mapping_channel=official
mapping_version=1.16.5
ae2_version=8.4.7

mod_id=expansionae
mod_name=ExpansionAE
mod_license=LGPL-3.0
mod_version=1.16.5-0.1.0-dev
mod_group_id=dev.bulkcloud.expansionae
mod_authors=Pedroksl, GlodBlock; ExpansionAE merge/backport by BulkCloud0
mod_description=Unified Minecraft 1.16.5 Forge backport of AdvancedAE and ExtendedAE for Applied Energistics 2.
